import PackerImage from "/vacancy/cosmetic-package.png";
import ChineseRestaurant from "/vacancy/chinese-restaraunt.png";
import HotelMaids from "/vacancy/hotel-maids.png";
import MushroomFarm from "/vacancy/mushroom-farm.png";

export const VACANCIES = [
  {
    image: PackerImage,
    name: "Упаковщик на склад одежды аксессуаров Amazon ",
    country: "Великобритания",
    category: "Упаковщик",
    age: "20-40",
    salary: "2000$ - 2500$",
    employment: "Полная",
    gender: "Мужчины/женщины",
    workPlace: "Склад",
    languageSkill: true,
    house: false,
  },
  {
    image: ChineseRestaurant,
    name: "Упаковщик бижутерии и украшений Victoria's Secret",
    country: "Великобритания",
    category: "Упаковщик",
    age: "20-40",
    salary: "1400$ - 1600$",
    employment: "Полная",
    gender: "Мужчины/женщины",
    workPlace: "Склад",
    languageSkill: true,
    house: false,
  },
  {
    image: HotelMaids,
    name: "Работник на мебельное производство SENKO",
    country: "Испания",
    category: "Мебельщик",
    age: "24-40",
    salary: "2500$ - 3500$",
    employment: "Частичная",
    gender: "Мужчины",
    workPlace: "Фабрика",
    languageSkill: true,
    house: false,
  },
  {
    image: MushroomFarm,
    name: "Работа на автомобильном заводе",
    country: "Германия",
    category: "Разнорабочий",
    age: "20-40",
    salary: "2000$ - 2500$",
    employment: "Частичная",
    gender: "Мужчины/женщины",
    workPlace: "Завод",
    languageSkill: true,
    house: false,
  },
  {
    image: PackerImage,
    name: "Упаковщик на склад одежды аксессуаров Amazon",
    country: "Великобритания",
    category: "Упаковщик",
    age: "20-40",
    salary: "2000$ - 2500$",
    employment: "Частичная",
    gender: "Мужчины/женщины",
    workPlace: "Склад",
    languageSkill: true,
    house: false,
  },
  // {
  //   image: ChineseRestaurant,
  //   name: "Упаковщик бижутерии и украшений Victoria's Secret",
  //   country: "Великобритания",
  //   category: "Упаковщик",
  //   age: "20-40",
  //   salary: "1400$ - 1600$",
  //   employment: "Частичная",
  //   gender: "Мужчины/женщины",
  //   workPlace: "Склад",
  //   languageSkill: true,
  //   house: false,
  // },
  // {
  //   image: HotelMaids,
  //   name: "Работник на мебельное производство SENKO",
  //   country: "Испания",
  //   category: "Мебельщик",
  //   age: "24-40",
  //   salary: "2500$ - 3500$",
  //   employment: "Полная",
  //   gender: "Мужчины",
  //   workPlace: "Фабрика",
  //   languageSkill: true,
  //   house: false,
  // },
  // {
  //   image: MushroomFarm,
  //   name: "Работа на автомобильном заводе",
  //   country: "Германия",
  //   category: "Разнорабочий",
  //   age: "20-40",
  //   salary: "2000$ - 2500$",
  //   employment: "Полная",
  //   gender: "Мужчины/женщины",
  //   workPlace: "Завод",
  //   languageSkill: true,
  //   house: false,
  // },
  // {
  //   image: PackerImage,
  //   name: "Упаковщик на склад одежды аксессуаров Amazon",
  //   country: "Великобритания",
  //   category: "Упаковщик",
  //   age: "20-40",
  //   salary: "2000$ - 2500$",
  //   employment: "Полная",
  //   gender: "Мужчины/женщины",
  //   workPlace: "Склад",
  //   languageSkill: true,
  //   house: false,
  // },
  // {
  //   image: ChineseRestaurant,
  //   name: "Упаковщик бижутерии и украшений Victoria's Secret",
  //   country: "Великобритания",
  //   category: "Мебельщик",
  //   age: "20-40",
  //   salary: "1400$ - 1600$",
  //   employment: "Полная",
  //   gender: "Женщины",
  //   workPlace: "Склад",
  //   languageSkill: true,
  //   house: false,
  // },
  // {
  //   image: HotelMaids,
  //   name: "Работник на мебельное производство SENKO",
  //   country: "Испания",
  //   category: "Мебельщик",
  //   age: "24-40",
  //   salary: "2500$ - 3500$",
  //   employment: "Полная",
  //   gender: "Мужчины",
  //   workPlace: "Фабрика",
  //   languageSkill: true,
  //   house: false,
  // },
  // {
  //   image: MushroomFarm,
  //   name: "Работа на автомобильном заводе",
  //   country: "Германия",
  //   category: "Разнорабочий",
  //   age: "20-40",
  //   salary: "2000$ - 2500$",
  //   employment: "Полная",
  //   gender: "Женщины",
  //   workPlace: "Завод",
  //   languageSkill: true,
  //   house: false,
  // },
];
