import { IVacancy } from "./pagination";

import {
  MushroomFarm,
  PackerImage,
  ChineseRestaurant,
  HotelMaids,
} from "./VACANCIES_IMAGE";
export const VACANCIES = [
  {
    name: "Водитель-курьер DHL",
    salary: "2000-2200€",
    country: "Германия",
    category: "Курьер",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
    image: PackerImage,
  },
  {
    name: "Кровельщик-плотник",
    salary: "2800-2950€",
    country: "Германия",
    category: "Кровельщик-плотник",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "300€ / месяц",
    employment: "Частичная",
    image: ChineseRestaurant,
  },
  {
    name: "Водитель кат. В",
    salary: "2500-2700€",
    country: "Германия",
    category: "Водитель",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
    image: ChineseRestaurant,
  },
  {
    name: "Горничная круизного лайнера",
    salary: "2500-2700€",
    country: "Германия",
    category: "Горничная",
    gender: "Женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
    image: ChineseRestaurant,
  },
  {
    name: "Курьер Glovo",
    salary: "2500-2800€",
    country: "Эстония",
    category: "Курьер",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
    image: PackerImage,
  },
  {
    name: "Водители категории 'B' на доставку медикаментов 'Trans-o-flex'",
    salary: "3100-3300€",
    country: "Германия",
    category: "Водитель",
    gender: "Мужчины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
    image: ChineseRestaurant,
  },
  {
    name: "BABORD SEAFOOD AS Переработка рыбы",
    salary: "3100-3300€",
    country: "Норвегия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "300€ / месяц",
    employment: "Полная",
    image: MushroomFarm,
  },
  {
    name: "Штукатур-1",
    salary: "2300-2700€",
    country: "Германия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "300€ / месяц",
    employment: "Полная",
    image: ChineseRestaurant,
  },
  {
    name: "Работа в теплицах в Лондоне",
    salary: "2300-2500€",
    country: "Англия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
    image: PackerImage,
  },
  {
    name: "Работа на складе KINDER",
    salary: "3200-3600€",
    country: "Англия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
    image: ChineseRestaurant,
  },
  {
    name: "Упаковщики на склад магазина Reebok",
    salary: "3200-3450€",
    country: "Англия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
    image: MushroomFarm,
  },
  {
    name: "Разнорабочий в теплицы в Ливерпуле",
    salary: "2300-2700€",
    country: "Англия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
    image: PackerImage,
  },
  {
    name: "Разнорабочий на грибную ферму",
    salary: "3700-4000€",
    country: "Англия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "400€ / месяц",
    employment: "Полная",
    image: ChineseRestaurant,
  },
  {
    name: "Сбор и упаковка овощей на складе",
    salary: "2900-3200€",
    country: "Англия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "350€ / месяц",
    employment: "Полная",
    image: PackerImage,
  },
  {
    name: "Разнорабочий в Отель Park Plaza County Hall",
    salary: "3200-3400€",
    country: "Англия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
    image: ChineseRestaurant,
  },
  {
    name: "Упаковщик на склад Магазина Nike",
    salary: "3400-3700€",
    country: "Англия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "300€ / месяц",
    employment: "Частичная",
    image: ChineseRestaurant,
  },
  {
    name: "Работник на производстве Coca-Cola",
    salary: "3800€",
    country: "Англия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "400€ / месяц",
    employment: "Полная",
    image: ChineseRestaurant,
  },
  {
    name: "Упаковщик на склад магазина Zara",
    salary: "2800-3800€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "230€ / месяц",
    employment: "Частичная",
    image: MushroomFarm,
  },
  {
    name: "Рабочие на склад цветов Pijnacker",
    salary: "2900-3400€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
    image: ChineseRestaurant,
  },
  {
    name: "Рабочие на склад магазина Adidas",
    salary: "2700-3000€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Полная",
    image: MushroomFarm,
  },
  {
    name: "Рабочие на склад Philips в Амстердаме",
    salary: "2700-3000€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Частичная",
    image: PackerImage,
  },
  {
    name: "Упаковщики на склад чая компании Tess",
    salary: "2800-3300€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Полная",
  },
  {
    name: "Повар в сеть отелей или ресторанов",
    salary: "3000€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Мастер наращивания ресниц",
    salary: "1700-2100€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Женщины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Полная",
  },
  {
    name: "Строитель на внутренние работы в Гааге",
    salary: "4000-4500€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Мужчины",
    languageSkill: "Без знания языка",
    house: "350€ / месяц",
    employment: "Полная",
  },
  {
    name: "Официант в сеть ресторанов De Leuf",
    salary: "2200-2450€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Мужчины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Частичная",
  },
  {
    name: "Автомеханик в СТО",
    salary: "3000-3200€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Мужчины",
    languageSkill: "Без знания языка",
    house: "450€ / месяц",
    employment: "Полная",
  },
  {
    name: "Маляр с опытом работы",
    salary: "2500-2790€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Мужчины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Кузовщик/Рихтовщик/Маляр",
    salary: "3400-3900€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Мужчины",
    languageSkill: "Без знания языка",
    house: "350€ / месяц",
    employment: "Частичная",
  },
  {
    name: "Сортировщик стеклотары",
    salary: "2100-2400€",
    country: "Германия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Упаковка фисташек на складе",
    salary: "2100-2400€",
    country: "Германия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Упаковщик промтоваров на складе",
    salary: "2100-2400€",
    country: "Германия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Разнорабочий в сети китайских ресторанов",
    salary: "1900-2200€",
    country: "Германия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Работа на стикеровке товаров",
    salary: "2100-2400€",
    country: "Чехия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Работа на складе магазина DM",
    salary: "2100-2400€",
    country: "Чехия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Оператор производства фар к автомобилям",
    salary: "2600-2900€",
    country: "Чехия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Работа на автозаводе",
    salary: "2300-2600€",
    country: "Чехия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Работа на Автозаводе Ideal Automotive",
    salary: "2000-2200€",
    country: "Чехия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Работник на Склад Adidas & Tchibo",
    salary: "2100-2400€",
    country: "Чехия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Продуктовый склад-супермаркет ROHLIK",
    salary: "2100-2200€",
    country: "Чехия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Автомобильный завод Hutchinson",
    salary: "2100-2300€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Упаковка шоколадных изделий",
    salary: "2500-2700€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Повар-Сушист",
    salary: "2000-2100€",
    country: "Польша",
    category: "Повар",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Работники в отель 'Harmony Bay Hotel'",
    salary: "2500-2700€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Установка солнечных панелей",
    salary: "2500-2700€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Полная",
  },
  {
    name: "Работники на картофельную ферму",
    salary: "2300-2500€",
    country: "Германия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Полная",
  },
  {
    name: "Работа на норковой ферме",
    salary: "2100-2300€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Полная",
  },
  {
    name: "Сбор помидоров/перцев в теплицах",
    salary: "2100-2300€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Частичная",
  },
  {
    name: "Склад интернет магазина",
    salary: "2100-2300€",
    country: "Венгрия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Уборка в госпитале",
    salary: "2100-2300€",
    country: "Польша",
    category: "Уборщик",
    gender: "Женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Работа на стройке, установка фасада",
    salary: "2100-2300€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Водитель вилочного автопогрузчика",
    salary: "2100-2300€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "120€ / месяц",
    employment: "Частичная",
  },
  {
    name: "Работа на складе 'ACTION'",
    salary: "2000-2600€",
    country: "Германия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "120€ / месяц",
    employment: "Полная",
  },
  {
    name: "Работа на производстве деталей для BMW",
    salary: "2000-2200€",
    country: "Германия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Полная",
  },
  {
    name: "Складской работник",
    salary: "2100-2300€",
    country: "Венгрия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Частичная",
  },
  {
    name: "Работа на производственном заводе Porsche - 5",
    salary: "2100-2300€",
    country: "Германия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "365€ / месяц",
    employment: "Полная",
  },
  {
    name: "Работа на Мебельном заводе",
    salary: "1800-2000€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "160€ / месяц",
    employment: "Частичная",
  },
  {
    name: "Работа на Производстве Karcher",
    salary: "1800-2000€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "160€ / месяц",
    employment: "Полная",
  },
  {
    name: "Водитель фуры с категорией СЕ",
    salary: "3000-3100€",
    country: "Польша",
    category: "Водитель",
    gender: "Мужчины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Электромонтажник",
    salary: "2000-2100€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Оператор промышленной линии фирмы VICI",
    salary: "1800-2100€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Работники на упаковку мягких игрушек Chicco",
    salary: "2400€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Комплектовщик на складе одежды H&M",
    salary: "2400€",
    country: "Литва",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Работа по прокату проволоки",
    salary: "2100€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Склад интернет магазина Zalando",
    salary: "1800€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Склад продуктового магазина Zabka",
    salary: "1600€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Очистка линий электропередач",
    salary: "2400€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Работа курьером по доставке интернет заказов в компании GLS",
    salary: "2400€",
    country: "Польша",
    category: "Курьер",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Работа на лесопилке",
    salary: "2200€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Работа курьером по доставке интернет заказов в Гамбурге",
    salary: "2200€",
    country: "Германия",
    category: "Курьер",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Сбор помидоров/перцев в теплицах",
    salary: "2400€",
    country: "Нидерланды",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Частичная",
  },
  {
    name: "Оператор прессовых машин на завод по производству автомобильных зеркал",
    salary: "2100€",
    country: "Венгрия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "Бесплатно",
    employment: "Полная",
  },
  {
    name: "Комплектовщик на склад в супермаркет Biedronka",
    salary: "2100€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "250€ / месяц",
    employment: "Частичная",
  },
  {
    name: "Работа на складе Toyota",
    salary: "2200€",
    country: "Польша",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "280€ / месяц",
    employment: "Полная",
  },
  {
    name: "Водитель штабелера",
    salary: "2200€",
    country: "Венгрия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "180€ / месяц",
    employment: "Частичная",
  },
  {
    name: "Завод пластиковых изделий",
    salary: "2200€",
    country: "Венгрия",
    category: "Разнорабочий",
    gender: "Мужчины/женщины",
    languageSkill: "Без знания языка",
    house: "210€ / месяц",
    employment: "Полная",
  },
];
